gcc: Fix compilation warning due to missing main() declaration
gcc_startup_lpc8xx.c: In function 'ResetISR':
gcc_startup_lpc8xx.c:177:5: warning: implicit declaration of function 'main' [-Wimplicit-function-declaration]
     main();
     ^~~~